### ISSUE TITLE
Please finish the Readme

### ISSUE THREAD

**Issue by Sri115** [loeeeee/immich-in-lxc#1]
The Instructions stops at "After creating the user,". Would really appreciate if you could continue. My expectation is that we just need to run the script but it would be nice to know if there are further steps.

**Comment by loeeeee** [comment]
Sure, working on that now! :)

**Comment by loeeeee** [comment]
The install script and the README is now brought to a almost latest release, v1.110.0, (Immich is now at v1.111.0).

I will check compatibility with the latest one later.

**Comment by loeeeee** [comment]
It is working now with latest immich release! 26d9b9ae95b51a2ca74300f99921afc1fbc15828

**Comment by Sri115** [comment]
Thank you for your quick work going above and beyond what was requested. Can't wait to try it out

**Comment by Sri115** [comment]
Got immich v1.111.0 up an running with ML and transcoding thanks to you. Only place I had difficulty was installing libcublaslt12 and libcublas12.

I had to use instructions from [Nvidia developer](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=12&target_type=deb_local). But thanks a lot for your excellent work.

**Comment by loeeeee** [comment]
> Got immich v1.111.0 up an running with ML and transcoding thanks to you. Only place I had difficulty was installing libcublaslt12 and libcublas12.
> 
> I had to use instructions from [Nvidia developer](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=12&target_type=deb_local). But thanks a lot for your excellent work.

Great to hear that!

It seems that LXC users like to use `Debian` quite more than I expected. So, I will test the script a bit more on Debian, and ironing out those frustrations.

Thanks for your encouragement!
