### ISSUE TITLE
DB_PASSWORD in runtime.env Not Being Used by Immich on Debian 12

### ISSUE THREAD

**Issue by makovez** [loeeeee/immich-in-lxc#11]
I'm encountering an issue where the DB_PASSWORD specified in the runtime.env file is not being used when Immich tries to connect to the PostgreSQL database. If I change the DB_PASSWORD in runtime.env, Immich still attempts to connect with the previous password, resulting in a connection failure.

**Comment by loeeeee** [comment]
Sorry, this is a busy week for me. I will look into this at weekend.

**Comment by loeeeee** [comment]
Just in case, you changed the password inside `/home/immich/runtime.env`? Not the one in `immich-in-lxc`, right?

To be honest, I do not have many clues on this.

Can you try run `/home/immich/app/start.sh immich` as user immich, after stopping the system unit service? And tests out if the modification to the runtime.env works?

**Comment by makovez** [comment]
oh yeah i did.  I mean, i set it first inside` immich-in-lxc` and after running ./install it copied the same in `/home/immich/runtime.env`, so i just made sure the password was there too, and it was.

**Comment by makovez** [comment]
![image](https://github.com/user-attachments/assets/83f7a921-463e-437c-afe3-31ed21072514)
Might be for this ? Is that ENV passed to api and microservices too ?

**Comment by loeeeee** [comment]
> Might be for this ? Is that ENV passed to api and microservices too ?

They should all have been passed to microservices, and web(i.e. API). Otherwise, they would not start. The `immich/app/start.sh` contains the code to load the environment file.

Can you try renaming `runtime.env` in `/home/immich/` to something else and check if it would start? I am now quite confused of how this could happen.

**Comment by makovez** [comment]
I just changed password and it seems working now, maybe i messed sth up before. Sorry about that.

**Comment by loeeeee** [comment]
> I just changed password and it seems working now, maybe i messed sth up before. Sorry about that.

Never mind. 😃 Thanks for working together!
