### ISSUE TITLE
Use base image of immich to build dependency

### ISSUE THREAD

**Issue by loeeeee** [loeeeee/immich-in-lxc#21]
Immich has a [base image script](https://github.com/immich-app/base-images). It is a cheatsheet for making LXC version better.

**Comment by 2600box** [comment]
This could be important for the issues reported here: https://github.com/immich-app/immich/discussions/12241#discussioncomment-10528560

Seems that some minor variation in dependencies causes a problem with creating thumbnails of some .heic files.

**Comment by loeeeee** [comment]
> This could be important for the issues reported here: [immich-app/immich#12241 (comment)](https://github.com/immich-app/immich/discussions/12241#discussioncomment-10528560)
> 
> Seems that some minor variation in dependencies causes a problem with creating thumbnails of some .heic files.

Thanks for bring up related issue. I am now looking into it. Currently, I have completed the local building process, but I am not sure how to make Immich using it. It will probably get fixed  this week.

**Comment by loeeeee** [comment]
Related errors:
> [Nest] 526  - 09/07/2024, 8:23:56 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-preview): Error: upload/upload/57860762-01cd-4204-abdb-e5ad147c82f7/33/45/3345176c-cd80-4463-835f-c7a683b0382a.heic: bad seek to 2540027
heif: Error while loading plugin: No decoding plugin installed for this compression format (11.6003)
[Nest] 526  - 09/07/2024, 8:23:56 AM   ERROR [Microservices:JobService] Error: upload/upload/57860762-01cd-4204-abdb-e5ad147c82f7/33/45/3345176c-cd80-4463-835f-c7a683b0382a.heic: bad seek to 2540027
heif: Error while loading plugin: No decoding plugin installed for this compression format (11.6003)
    at Sharp.toFile (/home/immich/app/node_modules/sharp/lib/output.js:90:19)
    at MediaRepository.generateThumbnail (/home/immich/app/dist/repositories/media.repository.js:69:14)
    at MediaService.generateThumbnail (/home/immich/app/dist/services/media.service.js:176:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGeneratePreview (/home/immich/app/dist/services/media.service.js:141:29)
    at async /home/immich/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/home/immich/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/home/immich/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 526  - 09/07/2024, 8:23:56 AM   ERROR [Microservices:JobService] Object:
{
  "id": "0d1eb272-bcdc-4619-9c58-92fab32f7fb1",
  "source": "upload"
}

**Comment by loeeeee** [comment]
> This could be important for the issues reported here: [immich-app/immich#12241 (comment)](https://github.com/immich-app/immich/discussions/12241#discussioncomment-10528560)
> 
> Seems that some minor variation in dependencies causes a problem with creating thumbnails of some .heic files.

This [issue](https://github.com/loeeeee/immich-in-lxc/issues/24#issue-2511847533) will continue the topic.

**Comment by loeeeee** [comment]
Fixed in 0b89a2e330549187b27ebb9e57607f96f67d1a11
