### ISSUE TITLE
E: Unable to locate package libspng-dev

### ISSUE THREAD

**Issue by macminoz** [loeeeee/immich-in-lxc#26]
Using Ubuntu 22.04-1_amd64 LXC container under Proxmox 8.2, I get this:

`root@immich:/home/immich/immich-in-lxc# ./dep-ubuntu.sh
+ ./dep-common.sh
+ apt install curl git python3-venv python3-dev build-essential unzip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
curl is already the newest version (7.81.0-1ubuntu1.17).
git is already the newest version (1:2.34.1-1ubuntu1.11).
python3-dev is already the newest version (3.10.6-1~22.04.1).
unzip is already the newest version (6.0-26ubuntu3.2).
python3-venv is already the newest version (3.10.6-1~22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ apt install --no-install-recommends -y autoconf build-essential cmake jq perl libnet-ssleay-perl libio-socket-ssl-perl libcapture-tiny-perl libfile-which-perl libfile-chdir-perl libpkgconfig-perl libffi-checklib-perl libtest-warnings-perl libtest-fatal-perl libtest-needs-perl libtest2-suite-perl libsort-versions-perl libpath-tiny-perl libtry-tiny-perl libterm-table-perl libany-uri-escape-perl libmojolicious-perl libfile-slurper-perl libde265-dev libexif-dev libexpat1-dev libglib2.0-dev libgsf-1-dev liblcms2-2 liborc-0.4-dev librsvg2-dev libspng-dev meson ninja-build pkg-config wget zlib1g cpanminus libltdl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package libspng-dev**`

even if I have installed it already:

`root@immich:/home/immich/immich-in-lxc# apt-get -y install libpng-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**libpng-dev is already the newest version (1.6.37-3build5).**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

thanks

**Comment by loeeeee** [comment]
Also, can you try install Immich on Ubuntu 24.04, since it is the latest LTS release? Or is there any specific reason that you have to use Ubuntu 22.04?

**Comment by loeeeee** [comment]
Bro forgot his GitHub account, and I cannot find further todo in the issue. Now closing. 🥹
