### ISSUE TITLE
Error on onnxruntime:Default, libcudnn.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zezhenwang** [loeeeee/immich-in-lxc#32]
I am running into the following issue when trying to install this on a Ubuntu server:

E:onnxruntime:Default, provider_bridge_ort.cc:1745 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory

+ Here's a link to the screenshot: https://pasteboard.co/4bax4UZWZRIv.png

**Comment by loeeeee** [comment]
> For Immich machine learning support, we also need to install CuDNN and two additional libraries,
> ```bash
> apt install nvidia-cudnn libcublaslt12 libcublas12
> ```

Since you are using Ubuntu, can you check if you have these libraries installed?

**Comment by zezhenwang** [comment]
My bad. I saw it brought up in another issue.

**Comment by loeeeee** [comment]
> My bad. I saw it brought up in another issue #7.

Never mind. 😂
