### ISSUE TITLE
Upgrade Immich to v1.116.2

### ISSUE THREAD

**Issue by loeeeee** [loeeeee/immich-in-lxc#33]
They have not made new release for so long that I thought they go for a rolling release.

**Comment by xury77** [comment]
Please any hints how to use hw with Intel 12gen vaapi or qsv machine lerning gpu support.

**Comment by loeeeee** [comment]
> Please any hints how to use hw with Intel 12gen vaapi or qsv machine lerning gpu support.

Hi @xury77 ,

Since this is a issue relating to upgrade Immich version, and I will be closing this issue very soon, would you please open two issues about these two topics, *the VAAPI one* and *the ML one*? Then we can together figure out the solution and other people with similar issues can easily find what they need to know. 😄

**Comment by loeeeee** [comment]
Finished in 687e48ad0b80d3e0af39ecace7cbba5c1a41da6d
