### ISSUE TITLE
base-images/server/bin/build-lock.json

### ISSUE THREAD

**Issue by jrogers512** [loeeeee/immich-in-lxc#39]
Trying to follow the readme, using Debian Bookworm, and after running `./install.sh`, I see this error:

``` shell
+ cp base-images/server/bin/build-lock.json /home/immich/app/
cp: cannot stat 'base-images/server/bin/build-lock.json': No such file or directory
```

I don't see base-images anywhere, and am not sure how to troubleshoot further.

**Comment by loeeeee** [comment]
Hi @jrogers512,

The base-image is downloaded at the *pre-install* step, where many libraries are compiled locally. Can you try to run `pre-install.sh` again as a root user? 😄 

Best,
Loe

**Comment by loeeeee** [comment]
Bro forgot his GitHub password 😢
