### ISSUE TITLE
immich-web.service requires immich-microservices.service

### ISSUE THREAD

**Issue by ahmadhadidi** [loeeeee/immich-in-lxc#47]
Hi Loeeeee,

When I run the step:
``` bash
systemctl daemon-reload && \
systemctl start immich-ml && \
systemctl start immich-web
```

it says that `immich-microservices` is not found, I removed the line that requires `immich-web.service` from the file `immich-web.service`. Is that correct?

**Comment by loeeeee** [comment]
Hi @ahmadhadidi,

Yes, that is correct.

Because Immich removed dedicated microservices backend on version 1.118.0, people upgrade from previous version needs some manual changes to the setup as well. The detailed setup change can be found at pinned issue #44.

**Comment by ahmadhadidi** [comment]
Great thanks for letting me know :)
