### ISSUE TITLE
The script post-install.sh fails on rm

### ISSUE THREAD

**Issue by DenisSolonevich** [loeeeee/immich-in-lxc#61]
I just followed the guide on the Debian 12 in LXC container of Proxmox (but all this doesn't matter actually) 
The "rm" command in the post-install.sh can't find "immich-microservices.service" so it stops the execution and don't actually copy new services.

**Comment by DenisSolonevich** [comment]
Thank you! I didn't try it because solved it locally but I'm pretty sure "-f" should do the job :-)

**Comment by loeeeee** [comment]
Glad to hear that.

Problem solved then.

Feel free to reopen the issue. 😃
